/// <reference types="vitest/globals" />
import { readFile } from 'fs/promises';
import { fileURLToPath } from 'url';
import path from 'path';
import { describe, test, expect, beforeAll } from 'vitest';
import { resize as tsResize } from './carver';

// wasm-bindgen --target web generates an init() default export and named exports
// eslint-disable-next-line @typescript-eslint/no-explicit-any
let wasmInit: (input: { module_or_path: BufferSource }) => Promise<any>;
let wasmResize: (
  pixels: Uint8Array,
  width: number,
  height: number,
  derivative: string,
  targetWidth: number,
  targetHeight: number,
) => Uint8Array;

describe('cross-engine consistency', () => {
  beforeAll(async () => {
    // Dynamically import the WASM glue code (generated by build:wasm)
    const wasm = await import('../wasm/pkg/carver_wasm.js');
    wasmInit = wasm.default;
    wasmResize = wasm.resize;

    // In Node/Vitest, init() can't fetch — pass the .wasm bytes directly.
    // Resolve path relative to this test file using fileURLToPath for Node compatibility.
    const thisDir = path.dirname(fileURLToPath(import.meta.url));
    const wasmPath = path.resolve(thisDir, '../wasm/pkg/carver_wasm_bg.wasm');
    const wasmBytes = await readFile(wasmPath);
    await wasmInit({ module_or_path: wasmBytes });
  });

  const testPixels = new Uint8ClampedArray([
    238, 226, 86, 255, 255, 252, 96, 255, 255, 255, 109, 255, 255, 255, 117, 255,
    84, 83, 58, 255, 131, 131, 80, 255, 151, 150, 76, 255, 196, 193, 68, 255,
    73, 75, 77, 255, 68, 69, 76, 255, 41, 43, 55, 255, 30, 25, 17, 255,
    28, 28, 26, 255, 28, 29, 25, 255, 0, 0, 17, 255, 159, 138, 26, 255,
  ]);

  test('WASM and TS produce identical output for sobel 4x4 → 3x3', () => {
    const input = new ImageData(testPixels.slice(), 4, 4);
    const tsResult = tsResize(input, 'sobel', 3, 3);
    const wasmResult = wasmResize(new Uint8Array(testPixels), 4, 4, 'sobel', 3, 3);

    expect(wasmResult).toEqual(new Uint8Array(tsResult.data.buffer));
  });

  test('WASM and TS produce identical output for simple 4x4 → 2x4', () => {
    const input = new ImageData(testPixels.slice(), 4, 4);
    const tsResult = tsResize(input, 'simple', 2, 4);
    const wasmResult = wasmResize(new Uint8Array(testPixels), 4, 4, 'simple', 2, 4);

    expect(wasmResult).toEqual(new Uint8Array(tsResult.data.buffer));
  });

  test('WASM and TS produce identical output for sobel 4x4 → 4x3 (horizontal-only)', () => {
    const input = new ImageData(testPixels.slice(), 4, 4);
    const tsResult = tsResize(input, 'sobel', 4, 3);
    const wasmResult = wasmResize(new Uint8Array(testPixels), 4, 4, 'sobel', 4, 3);

    expect(wasmResult).toEqual(new Uint8Array(tsResult.data.buffer));
  });
});
